name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    step:
      - name: Checkout
        uses: actions/checkout@v2
      - name: SetNodeVersion
        uses: actions/setup0node@v2
        with:
          npde-version: '14'
      - name: NodeCheck
        run: node -v
      - name: InstallAndBuild
        run: |
          npm ci
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: .
